typeof(1)
typeof(1.1)
typeof('1.1')
typeof(true)
typeof(null)
typeof(undefined)
typeof([])
typeof({})
typeof(NaN)
console.log(typeof(1));
console.log(typeof(1.1));
console.log(typeof('1.1'));
console.log(typeof(true));
console.log(typeof(null));
console.log(typeof(undefined));
console.log(typeof([]));
console.log(typeof({}));
console.log(typeof(NaN));
